MVCHomework_20170703/Models/ViewModels/CustomerBankViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCHomework_20170703.Models.ViewModels
{
    public class QueryCustomerBankViewModel
    {
        public int BankId { get; set; }
        public string CustomerName { get; set; }
    }
}

MVCHomework_20170703/Controllers/CustomerBankController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MVCHomework_20170703.Models;
using MVCHomework_20170703.Models.ViewModels;
using PagedList;
using ClosedXML.Excel;

namespace MVCHomework_20170703.Controllers
{
    [MyAuth]
    public class CustomerBankController : BaseController
    {
        客戶資料Repository customerRepo = RepositoryHelper.Get客戶資料Repository();
        客戶銀行資訊Repository customerBankRepo = RepositoryHelper.Get客戶銀行資訊Repository();
        int _pageSize = 5;

        // GET: CustomerBank
        public ActionResult Index(int pageNo = 1)
        {
            ViewBag.BankId = customerBankRepo.GetBankCodeList();

            //return View(customerBankRepo.All().Include(客 => 客.客戶資料));

            //增加分頁功能
            var tempData = customerBankRepo.All();
            var data = tempData.ToPagedList(pageNo, this._pageSize);

            return View(data);
        }

        [HttpPost]
        public ActionResult Index(QueryCustomerBankViewModel queryModel, int pageNo = 1, string sortName = "", string currentSortName = "")
        {
            if (ModelState.IsValid)
            {
                ViewBag.BankId = customerBankRepo.GetBankCodeList();
                ViewBag.CustomerName = queryModel.CustomerName;

                var tempData = customerBankRepo.All(queryModel, sortName, currentSortName);
                var data = tempData.ToPagedList(pageNo, this._pageSize);

                ViewData["CurrentSortName"] = currentSortName;
                ViewData["SortName"] = sortName;
                ViewData["PageNo"] = pageNo;

                return View(data);
            }

            return View();
        }

        //增加JsonResult使用範例
        public FileResult Excel(QueryCustomerBankViewModel queryModel)
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                var data = customerBankRepo.All(queryModel).Select(c => new { c.銀行名稱, c.銀行代碼, c.分行代碼, c.帳戶名稱, c.帳戶號碼, c.客戶資料.客戶名稱 });

                var ws = wb.Worksheets.Add("客戶銀行資料", 1);
                ws.Cell(1, 1).Value = "銀行名稱";
                ws.Cell(1, 2).Value = "銀行代碼";
                ws.Cell(1, 3).Value = "分行代碼";
                ws.Cell(1, 4).Value = "帳戶名稱";
                ws.Cell(1, 5).Value = "帳戶號碼";
                ws.Cell(1, 6).Value = "客戶名稱";

                ws.Cell(2, 1).InsertData(data);

                using (System.IO.MemoryStream memoryStream = new System.IO.MemoryStream())
                {
                    wb.SaveAs(memoryStream);
                    return File(memoryStream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Octet, "客戶銀行資料.xlsx");
                }
            }
        }

        //增加JsonResult使用範例
        public JsonResult CheckExcel(QueryCustomerBankViewModel queryModel)
        {
            var cnt = customerBankRepo.All(queryModel).Count();

            var routeValues = new System.Web.Routing.RouteValueDictionary(queryModel);
            var queryString = string.Empty;
            foreach (var item in routeValues)
            {
                if (!string.IsNullOrEmpty(queryString)) queryString += "&";
                queryString += item.Key + "=" + item.Value;
            }
            if (!string.IsNullOrEmpty(queryString)) queryString = "?" + queryString;

            var result = new
            {
                ExcelCount = cnt,
                ExcelUrl = string.Format("/{0}/Excel{1}", this.ControllerContext.RouteData.Values["controller"].ToString(), queryString)
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // GET: CustomerBank/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = customerBankRepo.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // GET: CustomerBank/Create
        public ActionResult Create()
        {
            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱");
            return View();
        }

        // POST: CustomerBank/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                customerBankRepo.Create(客戶銀行資訊);
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: CustomerBank/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = customerBankRepo.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // POST: CustomerBank/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                customerBankRepo.Modify(客戶銀行資訊);
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: CustomerBank/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = customerBankRepo.Find(id);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // POST: CustomerBank/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            customerBankRepo.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                customerBankRepo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCHomework_20170703/Views/CustomerBank/Create.cshtml
@model MVCHomework_20170703.Models.客戶銀行資訊

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCHomework_20170703/Views/CustomerBank/Delete.cshtml
@model MVCHomework_20170703.Models.客戶銀行資訊

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCHomework_20170703/Views/CustomerBank/Details.cshtml
@model MVCHomework_20170703.Models.客戶銀行資訊

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCHomework_20170703/Views/CustomerBank/Edit.cshtml
@model MVCHomework_20170703.Models.客戶銀行資訊

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCHomework_20170703/Views/CustomerBank/Index.cshtml
@model IEnumerable<MVCHomework_20170703.Models.客戶銀行資訊>
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = "客戶銀行資料";
}

@section navLink {
    <li><a href='/Index'><i class='fa fa-circle-o active'></i>@ViewBag.Title</a></li>
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary form-horizontal">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-search"></i>查詢條件</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool margin-l-10" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                @using (Html.BeginForm("Index", "CustomerBank", FormMethod.Post, new { id = "form1" }))
                {
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-2">
                                    <div class="label-wrapper">
                                        <label for="BankId" class="control-label">銀行代碼</label>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    @Html.DropDownList("BankId", null, htmlAttributes: new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-2">
                                    <div class="label-wrapper">
                                        <label for="CustomerName" class="control-label">客戶名稱</label>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    @Html.TextBox("CustomerName", null, new { @class = "search-text form-control", placeholder = "客戶名稱" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12" style="text-align: center">
                            <button type="submit" class="btn btn-default"><i class='fa fa-search'></i>查詢</button>
                            <p class="btn btn-success">
                                <a href='@Url.Action("Create")' style="color:white"><i class='fa fa-plus'></i>  新增</a>
                            </p>
                            <button type="button" onclick="buttonExport()" class="btn btn-info"><i class='fa fa-file-excel-o'></i> 匯出Excel</button>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">顯示資料</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool margin-l-10" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-12">
                    <div style="width: 100%; overflow: auto;">
                        <table class="table">
                            <tr>
                                <th nowrap>
                                    <a class="tableSort" href="bankName">@Html.DisplayNameFor(model => model.銀行名稱)<span class="sortOrder"></span></a>
                                </th>
                                <th nowrap>
                                    <a class="tableSort" href="bankCode">@Html.DisplayNameFor(model => model.銀行代碼)<span class="sortOrder"></span></a>
                                </th>
                                <th nowrap>
                                    <a class="tableSort" href="bankSubCode">@Html.DisplayNameFor(model => model.分行代碼)<span class="sortOrder"></span></a>
                                </th>
                                <th nowrap>
                                    <a class="tableSort" href="accountName">@Html.DisplayNameFor(model => model.帳戶名稱)<span class="sortOrder"></span></a>
                                </th>
                                <th nowrap>
                                    <a class="tableSort" href="account">@Html.DisplayNameFor(model => model.帳戶號碼)<span class="sortOrder"></span></a>
                                </th>
                                <th nowrap>
                                    <a class="tableSort" href="customerName">@Html.DisplayNameFor(model => model.客戶資料.客戶名稱)<span class="sortOrder"></span></a>
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td nowrap>
                                        @Html.DisplayFor(modelItem => item.銀行名稱)
                                    </td>
                                    <td nowrap>
                                        @Html.DisplayFor(modelItem => item.銀行代碼)
                                    </td>
                                    <td nowrap>
                                        @Html.DisplayFor(modelItem => item.分行代碼)
                                    </td>
                                    <td nowrap>
                                        @Html.DisplayFor(modelItem => item.帳戶名稱)
                                    </td>
                                    <td nowrap>
                                        @Html.DisplayFor(modelItem => item.帳戶號碼)
                                    </td>
                                    <td nowrap>
                                        @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
                                    </td>
                                    <td nowrap>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    @Html.PagedListPager(Model as IPagedList, (p) => Url.Action("Index", new { pageNo = p }))
                </div>
            </div>
        </div>
    </div>
    @Html.Hidden("Table_Sort", ViewData["SortName"])
    @Html.Hidden("Table_CurrentSortName", ViewData["CurrentSortName"])
    @Html.Hidden("Table_PageNo", ViewData["PageNo"])
</div>

@section scripts
{
    <script src="~/Scripts/pageAndSort.js"></script>
    <script src="~/Scripts/exportExcel.js"></script>
    <script type="text/javascript"> 
        function buttonExport() {
            CheckExportExcel("/CustomerBank/CheckExcel", { CustomerName: $("#CustomerName").val(), CustomerType: $("#CustomerType").val() });
        }
        initPageAndSort("/CustomerBank");
    </script>

}