MVCHomework_20170703/Models/ViewModels/CustomerContactViewModel.cs
using MVCHomework_20170703.Models.InputValidations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCHomework_20170703.Models.ViewModels
{
    public class QueryCustomerContactViewModel
    {
        public string CustomerName { get; set; }
        public string CustomerContactName { get; set; }
        public string JobTitle { get; set; }
    }

    public class CustomerContactBatchViewModel
    {  
        [Required]
        public int Id { get; set; } 

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [Required]
        public string 職稱 { get; set; } 

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        //[RegularExpression(@"^09\d{2}-\d{6}$", ErrorMessage = "手機格式必須為09xx-xxxxxx")] //簡單的驗證可以直接使用正則表達示即可
        [ValidateTaiwanMobile(ErrorMessage = "手機格式必須為09xx-xxxxxx")]
        public string 手機 { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        public string 電話 { get; set; } 
    }
}

MVCHomework_20170703/Controllers/CustomerContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCHomework_20170703.Models;
using MVCHomework_20170703.Models.ViewModels;
using PagedList;
using ClosedXML.Excel;

namespace MVCHomework_20170703.Controllers
{
    [MyAuth]
    public class CustomerContactController : BaseController
    {
        客戶資料Repository customerRepo = RepositoryHelper.Get客戶資料Repository();
        客戶聯絡人Repository customerContactRepo = RepositoryHelper.Get客戶聯絡人Repository();
        int _pageSize = 5;

        // GET: CustomerContact
        public ActionResult Index(int pageNo = 1)
        {
            //return View(customerContactRepo.All().Include(客 => 客.客戶資料));

            //增加分頁功能
            var tempData = customerContactRepo.All();
            var data = tempData.ToPagedList(pageNo, this._pageSize);

            return View(data);
        } 

        [HttpPost]
        public ActionResult Index(QueryCustomerContactViewModel queryModel, int pageNo = 1, string sortName = "", string currentSortName = "")
        {
            if (ModelState.IsValid)
            {
                ViewBag.CustomerName = queryModel.CustomerName;
                ViewBag.CustomerContactName = queryModel.CustomerContactName;
                ViewBag.JobTitle = queryModel.JobTitle;
                 
                var tempData = customerContactRepo.All(queryModel, sortName, currentSortName);
                var data = tempData.ToPagedList(pageNo, this._pageSize);

                ViewData["CurrentSortName"] = currentSortName;
                ViewData["SortName"] = sortName;
                ViewData["PageNo"] = pageNo;

                return View(data); 
            }

            return View();
        }

        //增加JsonResult使用範例
        public FileResult Excel(QueryCustomerContactViewModel queryModel)
        {
            using (XLWorkbook wb = new XLWorkbook())
            { 
                var data = customerContactRepo.All(queryModel).Select(c => new { c.職稱, c.姓名, c.Email, c.手機, c.電話, c.客戶資料.客戶名稱 });

                var ws = wb.Worksheets.Add("客戶聯絡人資料", 1);
                ws.Cell(1, 1).Value = "職稱";
                ws.Cell(1, 2).Value = "姓名";
                ws.Cell(1, 3).Value = "Email";
                ws.Cell(1, 4).Value = "手機";
                ws.Cell(1, 5).Value = "電話";
                ws.Cell(1, 6).Value = "客戶名稱";

                ws.Cell(2, 1).InsertData(data);

                using (System.IO.MemoryStream memoryStream = new System.IO.MemoryStream())
                {
                    wb.SaveAs(memoryStream);
                    return File(memoryStream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Octet, "客戶聯絡人資料.xlsx");
                }
            }
        }

        //增加JsonResult使用範例
        public JsonResult CheckExcel(QueryCustomerContactViewModel queryModel)
        {
            var cnt = customerContactRepo.All(queryModel).Count();

            var routeValues = new System.Web.Routing.RouteValueDictionary(queryModel);
            var queryString = string.Empty;
            foreach (var item in routeValues)
            {
                if (!string.IsNullOrEmpty(queryString)) queryString += "&";
                queryString += item.Key + "=" + item.Value;
            }
            if (!string.IsNullOrEmpty(queryString)) queryString = "?" + queryString;

            var result = new
            {
                ExcelCount = cnt,
                ExcelUrl = string.Format("/{0}/Excel{1}", this.ControllerContext.RouteData.Values["controller"].ToString(), queryString)
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // GET: CustomerContact/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = customerContactRepo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // GET: CustomerContact/Create
        public ActionResult Create()
        { 
            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱");
            return View();
        }

        // POST: CustomerContact/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                customerContactRepo.Create(客戶聯絡人);
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: CustomerContact/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = customerContactRepo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // POST: CustomerContact/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                customerContactRepo.Modify(客戶聯絡人);
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(customerRepo.All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: CustomerContact/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = customerContactRepo.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // POST: CustomerContact/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            customerContactRepo.Delete(id); 
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                customerContactRepo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCHomework_20170703/Views/CustomerContact/Create.cshtml
@model MVCHomework_20170703.Models.客戶聯絡人

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCHomework_20170703/Views/CustomerContact/Delete.cshtml
@model MVCHomework_20170703.Models.客戶聯絡人

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCHomework_20170703/Views/CustomerContact/Details.cshtml
@model MVCHomework_20170703.Models.客戶聯絡人

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCHomework_20170703/Views/CustomerContact/Edit.cshtml
@model MVCHomework_20170703.Models.客戶聯絡人

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCHomework_20170703/Views/CustomerContact/Index.cshtml
@model IEnumerable<MVCHomework_20170703.Models.客戶聯絡人>
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = "客戶聯絡人資料";
}

@section navLink {
    <li><a href='/Index'><i class='fa fa-circle-o active'></i>@ViewBag.Title</a></li>
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary form-horizontal">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-search"></i>查詢條件</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool margin-l-10" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                @using (Html.BeginForm("Index", "CustomerContact", FormMethod.Post, new { id = "form1" }))
                {
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-2">
                                    <div class="label-wrapper">
                                        <label for="CustomerName" class="control-label">客戶名稱</label>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    @Html.TextBox("CustomerName", null, new { @class = "search-text form-control", placeholder = "客戶名稱" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-2">
                                    <div class="label-wrapper">
                                        <label for="CustomerContactName" class="control-label">聯絡人姓名</label>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    @Html.TextBox("CustomerContactName", null, new { @class = "search-text form-control", placeholder = "聯絡人姓名" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-2">
                                    <div class="label-wrapper">
                                        <label for="JobTitle" class="control-label">職稱</label>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    @Html.TextBox("JobTitle", null, new { @class = "search-text form-control", placeholder = "職稱" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12" style="text-align: center">
                            <button type="submit" class="btn btn-default"><i class='fa fa-search'></i>查詢</button>
                            <p class="btn btn-success">
                                <a href='@Url.Action("Create")' style="color:white"><i class='fa fa-plus'></i>  新增</a>
                            </p>
                            <button type="button" onclick="buttonExport()" class="btn btn-info"><i class='fa fa-file-excel-o'></i> 匯出Excel</button>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="col-md-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">顯示資料</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool margin-l-10" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <div style="width: 100%; overflow: auto;">
                            <table class="table">
                                <tr>
                                    <th nowrap>
                                        <a class="tableSort" href="jobTitle">@Html.DisplayNameFor(model => model.職稱)<span class="sortOrder"></span></a>
                                    </th>
                                    <th nowrap>
                                        <a class="tableSort" href="name">@Html.DisplayNameFor(model => model.姓名)<span class="sortOrder"></span></a>
                                    </th>
                                    <th nowrap>
                                        <a class="tableSort" href="email">@Html.DisplayNameFor(model => model.Email)<span class="sortOrder"></span></a>
                                    </th>
                                    <th nowrap>
                                        <a class="tableSort" href="mobile">@Html.DisplayNameFor(model => model.手機)<span class="sortOrder"></span></a>
                                    </th>
                                    <th nowrap>
                                        <a class="tableSort" href="phone">@Html.DisplayNameFor(model => model.電話)<span class="sortOrder"></span></a>
                                    </th>
                                    <th nowrap>
                                        <a class="tableSort" href="customerName">@Html.DisplayNameFor(model => model.客戶資料.客戶名稱)<span class="sortOrder"></span></a>
                                    </th>
                                    <th></th>
                                </tr>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.職稱)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.姓名)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.手機)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.電話)
                                        </td>
                                        <td nowrap>
                                            @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
                                        </td>
                                        <td nowrap>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                        @Html.PagedListPager(Model as IPagedList, (p) => Url.Action("Index", new { pageNo = p }))
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Html.Hidden("Table_Sort", ViewData["SortName"])
    @Html.Hidden("Table_CurrentSortName", ViewData["CurrentSortName"])
    @Html.Hidden("Table_PageNo", ViewData["PageNo"])
</div>

@section scripts
{
    <script src="~/Scripts/pageAndSort.js"></script>
    <script src="~/Scripts/exportExcel.js"></script>
    <script type="text/javascript"> 
        function buttonExport() {
            CheckExportExcel("/CustomerContact/CheckExcel", { CustomerName: $("#CustomerName").val(), CustomerType: $("#CustomerType").val() });
        }
        initPageAndSort("/CustomerContact");
    </script>

}